# Generated by Django 5.0.14 on 2026-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_camera_anomaly_confidence_camera_anomaly_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='core.tracksection'),
        ),
    ]
