# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('Surface Crack', 'Surface Crack / Rolling Contact Fatigue'), ('Rail Corrosion', 'Rail Web & Base Corrosion'), ('Fastener Abnormality', 'Missing / Loose Rail Fastener / Clip'), ('Joint Abnormality', 'Fishplate & Insulated Joint Gap / Misalignment'), ('Surface Wear', 'Head Check Wear & Spalling'), ('Track-bed Issue', 'Ballast Void / Subgrade Scouring'), ('Foreign Object', 'Track Obstruction / Foreign Debris'), ('Unknown Anomaly', 'Unclassified Surface Irregularity')], default='Surface Crack', max_length=60)),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Severity')], default='MEDIUM', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=4, default=0.91, max_digits=5)),
                ('bounding_box', models.JSONField(default=dict, help_text='Normalized {x, y, width, height}')),
                ('explanation', models.TextField(help_text='Human-readable explanation of computer-vision findings')),
                ('recommended_action', models.TextField(default='Perform on-site ultrasonic verification within standard operating cycle.')),
                ('confirmed_by_engineer', models.BooleanField(default=False)),
                ('timestamp_in_video', models.CharField(blank=True, help_text='e.g. 00:14', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_url', models.CharField(default='/media/evidence/sample_track_raw.jpg', max_length=500)),
                ('annotated_image_url', models.CharField(default='/media/evidence/sample_track_annotated.jpg', max_length=500)),
                ('bounding_box_coordinates', models.JSONField(default=dict)),
                ('detection_label', models.CharField(default='Defect Contour Zone A', max_length=100)),
                ('optical_parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='inspections.anomaly')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_code', models.CharField(help_text='e.g. INS-2026-0142', max_length=40, unique=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('DRONE', 'Unmanned Aerial Inspection Drone'), ('PATROL_TRAIN', 'High-Speed Inspection Railcar'), ('FIXED_CAM', 'Trackside Automated Optical Array'), ('MANUAL', 'Field Inspector Handheld Scan'), ('VIDEO_INGEST', 'Recorded Video Feed Ingestion')], default='PATROL_TRAIN', max_length=30)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing Ingestion'), ('AI_COMPLETE', 'AI Analysis Complete'), ('AWAITING_REVIEW', 'Awaiting Engineer Review'), ('REVIEWED', 'Reviewed & Certified'), ('CLOSED', 'Action Closed')], default='AI_COMPLETE', max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Attention'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Immediate Action')], default='LOW', max_length=20)),
                ('ai_confidence', models.DecimalField(decimal_places=4, default=0.925, help_text='Aggregate AI Confidence (0.0000 - 1.0000)', max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.tracksection')),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='anomaly',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='inspections.inspection'),
        ),
        migrations.CreateModel(
            name='InspectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='inspections/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='inspections.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='inspections.inspectionmedia'),
        ),
    ]
