# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(help_text='e.g. REP-2026-0142', max_length=50, unique=True)),
                ('title', models.CharField(default='Certified Railway Infrastructure Inspection Dossier', max_length=200)),
                ('executive_summary', models.TextField()),
                ('ai_findings_section', models.JSONField(default=dict)),
                ('engineer_findings_section', models.JSONField(default=dict)),
                ('sensor_summary_section', models.JSONField(default=dict)),
                ('historical_growth_section', models.JSONField(default=dict)),
                ('compliance_standards', models.CharField(default='EN 50126 / FRA Track Safety Standards (49 CFR Part 213)', max_length=200)),
                ('is_signed_off', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inspections.inspection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
