# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('anomaly_category', models.CharField(default='Surface Crack', max_length=80)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('metric_name', models.CharField(default='Crack Length', help_text='e.g. Crack Length, Wear Depth, Joint Gap', max_length=80)),
                ('measured_value_mm', models.FloatField(default=4.2, help_text='Dimension in millimeters')),
                ('confidence_score', models.FloatField(default=0.92)),
                ('deterioration_index_at_time', models.IntegerField(default=45)),
                ('engineer_decision', models.CharField(default='CONFIRMED', max_length=30)),
                ('inspector_notes', models.TextField(blank=True, null=True)),
                ('image_snapshot_url', models.CharField(default='/media/evidence/history_crack_t1.jpg', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_entries', to='inspections.inspection')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_records', to='core.tracksection')),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value_mm', models.FloatField(default=4.2)),
                ('current_value_mm', models.FloatField(default=7.8)),
                ('delta_percentage', models.FloatField(default=85.71, help_text='% Growth rate')),
                ('time_elapsed_days', models.IntegerField(default=180)),
                ('wear_rate_mm_per_month', models.FloatField(default=0.6)),
                ('ai_risk_assessment', models.TextField(default='Accelerated growth trajectory observed. Surface fissure widening exceeds standard 0.2mm/month nominal threshold.')),
                ('previous_image_url', models.CharField(default='/media/evidence/historical_prev.jpg', max_length=500)),
                ('current_image_url', models.CharField(default='/media/evidence/historical_curr.jpg', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='core.tracksection')),
                ('baseline_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_comparisons', to='history.historicalrecord')),
                ('current_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_comparisons', to='history.historicalrecord')),
            ],
        ),
    ]
