# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('CONFIRM', 'Confirm AI Finding'), ('REJECT', 'Reject Finding (False Positive)'), ('NEEDS_FURTHER_INSPECTION', 'Needs Further On-Track Verification')], default='CONFIRM', max_length=40)),
                ('engineering_comment', models.TextField(help_text='Detailed engineering rationale and field maintenance instruction')),
                ('work_order_required', models.BooleanField(default=True, help_text='Flag whether field maintenance crew must be dispatched')),
                ('speed_restriction_required', models.BooleanField(default=False)),
                ('temporary_speed_limit_kmh', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='inspections.anomaly')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_reviews', to='inspections.inspection')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_category', models.CharField(default='Visual Bounding Box Accuracy', max_length=60)),
                ('rating_score', models.IntegerField(default=5, help_text='1 to 5 scale')),
                ('engineer_feedback_notes', models.TextField(blank=True, null=True)),
                ('is_used_for_retraining_evaluation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_records', to='ai_engine.aiprediction')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entry', to='reviews.engineerreview')),
            ],
        ),
    ]
