# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_vibration_rms', models.FloatField(default=2.4, help_text='Nominal baseline vibration in m/s^2')),
                ('baseline_temperature', models.FloatField(default=22.0, help_text='Nominal rail temperature in °C')),
                ('baseline_stress', models.FloatField(default=45.0, help_text='Nominal track stress in MPa')),
                ('baseline_axle_load', models.FloatField(default=22.5, help_text='Nominal axle load in Tonnes')),
                ('baseline_acoustic_db', models.FloatField(default=68.0, help_text='Nominal acoustic level in dB')),
                ('vibration_threshold_warn', models.FloatField(default=4.0)),
                ('vibration_threshold_crit', models.FloatField(default=6.5)),
                ('stress_threshold_warn', models.FloatField(default=65.0)),
                ('stress_threshold_crit', models.FloatField(default=85.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_baseline', to='core.tracksection')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vibration_rms', models.FloatField(help_text='RMS vibration in m/s^2')),
                ('rail_temperature', models.FloatField(help_text='Rail temperature in °C')),
                ('track_stress', models.FloatField(help_text='Track stress in MPa')),
                ('axle_load', models.FloatField(help_text='Axle load in Tonnes')),
                ('humidity', models.FloatField(default=55.0, help_text='Relative humidity %')),
                ('acoustic_db', models.FloatField(default=70.0, help_text='Acoustic emission in dB')),
                ('geometry_gauge_mm', models.FloatField(default=1435.0, help_text='Track gauge in mm (Standard: 1435mm)')),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_simulated', models.BooleanField(default=True)),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='core.tracksection')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
