# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='RailGuard-Vision-Multimodal-v3.2', max_length=100)),
                ('dataset_version', models.CharField(default='RailNet-Synthetic-2026.Q3', max_length=50)),
                ('precision', models.FloatField(default=0.942)),
                ('recall', models.FloatField(default=0.928)),
                ('f1_score', models.FloatField(default=0.935)),
                ('accuracy', models.FloatField(default=0.951)),
                ('total_predictions', models.IntegerField(default=1420)),
                ('reviewed_predictions', models.IntegerField(default=890)),
                ('confirmed_count', models.IntegerField(default=832)),
                ('rejected_count', models.IntegerField(default=38)),
                ('further_inspection_count', models.IntegerField(default=20)),
                ('human_agreement_pct', models.FloatField(default=93.48)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='RailGuard-Vision-v3.2', max_length=50)),
                ('predicted_anomaly_type', models.CharField(default='Surface Crack', max_length=80)),
                ('confidence', models.DecimalField(decimal_places=4, default=0.947, max_digits=5)),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('evidence_summary', models.TextField(help_text='Consolidated multi-modal evidence rationale')),
                ('visual_features', models.JSONField(default=dict)),
                ('sensor_features', models.JSONField(default=dict)),
                ('historical_features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='inspections.inspection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(help_text='e.g. Vision Agent, Sensor Agent, Risk Agent', max_length=50)),
                ('agent_role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Warning', 'Warning'), ('Error', 'Error')], default='Completed', max_length=20)),
                ('execution_time_ms', models.IntegerField(default=45)),
                ('confidence', models.FloatField(default=0.95)),
                ('findings_summary', models.TextField()),
                ('evidence_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='ai_engine.aiprediction')),
            ],
        ),
        migrations.CreateModel(
            name='DeteriorationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=68, help_text='0 (Healthy) to 100 (Critical)')),
                ('visual_factor', models.FloatField(default=35.0, help_text='Visual Defect contribution (35% weight)')),
                ('sensor_factor', models.FloatField(default=25.0, help_text='Sensor Deviation contribution (25% weight)')),
                ('historical_factor', models.FloatField(default=25.0, help_text='Historical Growth contribution (25% weight)')),
                ('recency_factor', models.FloatField(default=15.0, help_text='Inspection Recency contribution (15% weight)')),
                ('health_band', models.CharField(default='Watch / Elevated (50-74)', max_length=30)),
                ('explanation', models.TextField()),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterioration_scores', to='inspections.inspection')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deterioration_history', to='core.tracksection')),
            ],
            options={
                'ordering': ['-scored_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('CRITICAL', 'CRITICAL (6h Window)'), ('HIGH', 'HIGH (48h Window)'), ('MEDIUM', 'MEDIUM (14d Window)'), ('LOW', 'LOW (Routine Inspection)')], default='HIGH', max_length=20)),
                ('score', models.IntegerField(default=82)),
                ('contributing_reasons', models.JSONField(default=list)),
                ('recommended_action', models.TextField(default='Immediate track ultrasonic verification and visual manual inspection scheduled.')),
                ('dispatch_sla_hours', models.IntegerField(default=48)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_assignments', to='inspections.inspection')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='core.tracksection')),
            ],
            options={
                'ordering': ['-score', '-assigned_at'],
            },
        ),
    ]
