# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. USER_LOGIN, MEDIA_UPLOAD, AI_INFERENCE, ENGINEER_REVIEW', max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=60, null=True)),
                ('target_id', models.CharField(blank=True, max_length=60, null=True)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
