# Generated by Django 5.0.14 on 2026-09-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(help_text='e.g. TRK-001, TRK-014', max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. Northern Valley Mainline Segment 14', max_length=150)),
                ('line_type', models.CharField(choices=[('MAIN_LINE', 'Main Passenger Line'), ('HIGH_SPEED', 'High Speed Rail'), ('FREIGHT_CORRIDOR', 'Heavy Freight Corridor'), ('SUBURBAN', 'Suburban Transit'), ('SWITCH_YARD', 'Switching & Marshalling Yard')], default='MAIN_LINE', max_length=40)),
                ('start_km', models.DecimalField(decimal_places=3, default=0.0, help_text='Start kilometer marker', max_digits=8)),
                ('end_km', models.DecimalField(decimal_places=3, default=1.0, help_text='End kilometer marker', max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, default=37.7749, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=-122.4194, max_digits=10)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy (0-24)'), ('NORMAL', 'Normal Wear (25-49)'), ('WATCH', 'Watch / Elevated (50-74)'), ('HIGH', 'High Priority (75-89)'), ('CRITICAL', 'Critical Attention (90-100)')], default='HEALTHY', max_length=30)),
                ('deterioration_score', models.IntegerField(default=15, help_text='Composite Index 0 - 100')),
                ('max_speed_kmh', models.IntegerField(default=160, help_text='Current rated track speed limit')),
                ('electrified', models.BooleanField(default=True)),
                ('ballast_type', models.CharField(default='Crushed Granite Ballast', max_length=80)),
                ('sleeper_type', models.CharField(default='Prestressed Concrete Sleeper B70', max_length=80)),
                ('rail_profile', models.CharField(default='UIC 60 / 60E1', max_length=50)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section_code'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_code', models.CharField(help_text='e.g. CAM-014', max_length=30, unique=True)),
                ('name', models.CharField(default='Trackside Optical Sensor', max_length=120)),
                ('location_description', models.CharField(default='Overhead Gantry Station KP 14.2', max_length=255)),
                ('resolution', models.CharField(default='1080p 60fps', max_length=20)),
                ('stream_url', models.CharField(blank=True, default='simulated://feed/cam-014', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('firmware_version', models.CharField(default='v2.4.1-edge', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core.tracksection')),
            ],
            options={
                'ordering': ['camera_code'],
            },
        ),
    ]
