# Generated by Django 5.0.14 on 2026-09-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='anomaly_confidence',
            field=models.FloatField(default=0.947),
        ),
        migrations.AddField(
            model_name='camera',
            name='anomaly_label',
            field=models.CharField(blank=True, default='Surface Crack', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='anomaly_severity',
            field=models.CharField(default='HIGH', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(default='4K Optical Gantry Sensor', max_length=80),
        ),
        migrations.AddField(
            model_name='camera',
            name='fps',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='camera',
            name='has_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='km_marker',
            field=models.DecimalField(decimal_places=2, default=14.2, max_digits=8),
        ),
        migrations.AddField(
            model_name='camera',
            name='signal_quality',
            field=models.CharField(default='Good', max_length=30),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('LIVE', '● LIVE'), ('ONLINE', '● ONLINE'), ('OFFLINE', '○ OFFLINE'), ('CONNECTING', '◐ CONNECTING'), ('RECONNECTING', '↻ RECONNECTING')], default='LIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='ANOMALY_DETECTED', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('frame_snapshot_url', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
